default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
forest: styles/forest.scss
sakura: styles/sakura.scss
witches-town: styles/witches-town.scss
neoncity: styles/neon-city.scss
swan-lake: styles/swan-lake.scss
cyberpunk-neon: styles/cyberpunk-neon.scss
sleeping-town: styles/sleeping-town.scss
geodude: styles/geodude.scss
royal-tenenbaums: styles/royal-tenenbaums.scss
nga: styles/nga.scss
ubuntu-light: styles/ubuntu-light.scss
luxury: styles/luxury.scss
cybrespace: styles/cybre.scss
win95: styles/win95.scss
bingdaily: styles/bingdaily.scss
hellowland: styles/hellowland.scss
bilibili-light: styles/bilibili-light.scss
beebear: styles/beebear.scss
modern-dark: styles/modern-dark.scss
modern-light: styles/modern-light.scss
modern-contrast: styles/modern-contrast.scss
to-the-moon: styles/to-the-moon.scss
stardew-valley: styles/stardew-valley.scss
black-cat: styles/black-cat.scss
café: styles/café.scss